export type EmployeeRecord = {
    lastName: string
    firstName: string
    employeeUmbcEmail: string
    personalEmail: string
    filedBy: string
    countryOfBirth: string
    allCitizenships: string
    gender: string
    caseType: string
    permanentResidencyNotes: string
    dependents: number
    initialH1bStart: number
    startDate: number 
    expirationDate: number
    prepExtensionDate: number
    maxHPeriod: number
    documentExpiryI94: number
    generalNotes: string
    socCode: string
    socCodeDescription: string
    department: string
    employeeTitle: string
    departmentAdmin: string
    departmentAdvisorPiChair: string
    annualSalary: number
    employeeEducationalLevel: string
    employeeEducationalField: string
}